services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: reportes-db
    environment:
      POSTGRES_DB: reportes_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data: