spring:
  application:
    name: limpieza-publica-api

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  validation:
    enabled: true

  servlet:
    multipart:
      max-file-size: 5MB      # Límite por archivo
      max-request-size: 10MB  # Límite total por petición

logging:
  level:
    com.municipio.limpieza: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

cloudinary:
  cloud-name: dortn1fxq
  api-key: 519666568453567
  api-secret: naO__6TbtYJfPtDHwJzPmOQGg-E